version: '3.9'
services:
  api:
    container_name: api_service
    build:
      context: ./corridor_boilerplate/
      args:
        API_LAYER_PORT: ${API_LAYER_PORT}
    env_file:
      - .env
    ports:
      - "${API_LAYER_PORT}:${API_LAYER_PORT}"
    volumes:
      - ./corridor_boilerplate:/api-layer
    depends_on:
      - mongodb
      - mysql
  
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb_instance
    restart: always
    command: --quiet --logpath /dev/null 
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongodb:/data/db
  
  mysql:
    image: mysql:5.7
    container_name: mysql_instance
    restart: always
    environment:
      MYSQL_DATABASE: 'backend-sql-store'
      MYSQL_USER: 'user'      
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
    