# Generated by Django 4.1.7 on 2023-03-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDetails',
            fields=[
                ('doc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('devname', models.CharField(max_length=100)),
                ('modelname', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ModelDetails',
            },
        ),
    ]
