# Generated by Django 4.1.7 on 2023-03-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldetails',
            name='overview',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='reason',
            field=models.CharField(max_length=1000),
        ),
    ]
