# Generated by Django 4.1.7 on 2023-03-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmaker', '0002_alter_modeldetails_overview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldetails',
            name='overview',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='reason',
            field=models.CharField(max_length=10000),
        ),
    ]
